import Head from 'next/head'
import Typography from "@mui/material/Typography";
import React from "react";
import WorkoutTable from "@/components/WorkoutTable";
import {Button, Grid} from "@mui/material";
import Box from "@mui/material/Box";
import CreateFormComponent from "@/components/CreateEditForm";
import useSWR from 'swr';
import useAuthContext from "@/context/hooks/useAuthContext";
import Link from "next/link";

export interface IWorkout {
    _id: string;
    title: string;
    reps: number;
    load: number;
    createdAt: string;
}

export interface Props {
    rows?: IWorkout[];
}

export default function Home() {
    // const {rows} = props;
    const {user} = useAuthContext()
    const fetcher = async (url: string) => {
        const user = JSON.parse(localStorage.getItem('user') as any)
        const response = await fetch(url, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${user.token}`
            }
        });
        console.log('@@response', response)
        const rows = await response.json();
        return rows?.map((row: any) => ({...row, id: row._id})) ?? [];
    };

    const {data: rows, mutate} = useSWR<IWorkout[]>('http://localhost:8082/api/workouts', fetcher, {
        refreshInterval: 1000 * 60, // fetch data every minute
        revalidateOnMount: true, // fetch data when the component mounts
        revalidateOnReconnect: true, // fetch data when the network connection is restored
        shouldRetryOnError: true, // retry fetch when there's an error
    })
    return (
        <>
            <Head>
                <title>Blckclov3r</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Box>
                    {
                        user ?
                            <>
                                <Typography sx={{my: 4}} variant={'h5'}>Welcome <span
                                    style={{color: '#006699'}}>{user.email}</span></Typography>
                                <Grid container sx={{my: 4}} spacing={2}>
                                    <Grid item xs={3}>
                                        <Typography variant={"h5"}>Create</Typography>
                                        <CreateFormComponent mutate={mutate}/>
                                    </Grid>
                                    <Grid item xs={9}>
                                        <Typography variant={"h5"}>Lists</Typography>
                                        <WorkoutTable rows={rows ?? []} mutate={mutate}/>
                                    </Grid>
                                </Grid>
                            </>
                            :
                            <>
                                <Typography sx={{my: 4}} variant={'h5'}>Please login</Typography>
                                <Link href={'/login'}>
                                    <Button type="button" variant="contained" sx={{mb: 3}}>
                                        Login
                                    </Button>
                                </Link>
                                <Link href={'/register'}>
                                    <Typography variant={'body1'}>You do not have an account. Please register.</Typography>
                                </Link>
                            </>
                    }


                </Box>
            </main>
        </>
    )
}
